export const ADD_NOTE = "ADD_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const UPDATE_NOTE_CONTENT = "UPDATE_NOTE_CONTENT";
export const SAVE_NOTES = "SAVE_NOTES";
export const TOGGLE_INPUT_TEXT = "TOGGLE_INPUT_TEXT";
